
-- Global Gate Healthcare knowledge base
-- Source-only MySQL import generated strictly from the uploaded files:
-- 1) Instruction In Arabic 1.pdf
-- 2) Global Gate Healthcare new F.pptx

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS `global_gate_kb`;
CREATE DATABASE `global_gate_kb` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `global_gate_kb`;

CREATE TABLE `source_files` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `file_name` VARCHAR(255) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `notes` TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `knowledge_items` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `source_file_id` INT NOT NULL,
  `source_page` VARCHAR(50) NOT NULL,
  `section_name` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `language_code` VARCHAR(10) NOT NULL DEFAULT 'ar',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_knowledge_source_file`
    FOREIGN KEY (`source_file_id`) REFERENCES `source_files`(`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faq_items` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `question` TEXT NOT NULL,
  `answer` LONGTEXT NOT NULL,
  `source_file_id` INT NOT NULL,
  `source_page` VARCHAR(50) NOT NULL,
  `section_name` VARCHAR(255) NULL,
  `language_code` VARCHAR(10) NOT NULL DEFAULT 'ar',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_faq_source_file`
    FOREIGN KEY (`source_file_id`) REFERENCES `source_files`(`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `source_files` (`id`, `file_name`, `file_type`, `notes`) VALUES
(1, 'Instruction In Arabic 1.pdf', 'pdf', 'NCLEX Program instructions in Arabic'),
(2, 'Global Gate Healthcare new F.pptx', 'pptx', 'Global Gate Healthcare presentation');

INSERT INTO `knowledge_items` (`source_file_id`, `source_page`, `section_name`, `content`, `language_code`) VALUES
(1, '1', 'عنوان الملف', 'GLOBAL GATE HEALTHCARE (GGHC)\nCourse\nNCLEX Program\nInstructions In Arabic\nFall: 2025\nNablus /Ramallah /California\nPalestine-Middle East –USA', 'ar'),
(1, '2', 'الوثائق المطلوبة', 'الوثائق المطلوبة:\n- ارسال صورة عن جواز السفر ساري المفعول.\n- كشف الثانوية العامة (لغة انجليزية).\n- مغلفين من الجامعة (لغة انجليزية ومختوم من الاربع جهات يرجى عدم فتحه):\n  1) مغلف كشف علامات الشهادة الجامعية مع المصدقة من القبول والتسجيل مختوم من الاربع جهات يرجى عدم فتحه.\n  2) مغلف من قسم التمريض يكون فيه وصف المساقات ونموذج مختوم من عميد او رئيس قسم التمريض يصف عدد الساعات النظرية والعملية لكل مادة تخصصية (مختوم من الاربع جهات يرجى عدم فتحه).\n- مغلف النقابة (مختوم من الاربع جهات يرجى عدم فتحه):\n  1) حسن سير وسلوك من النقابة.\n  2) عضوية النقابة.\n  3) نموذج النقابة موقع من عطوفة النقيب باللغة الانجليزية.\n  4) جميعها باللغة الانجليزية في مغلف واحد مغلق مختوم.\nملاحظة: يجب ان يكون الاسم في جواز السفر الساري المفعول على الاقل لمدة سنتين وان يكون الاسم مطابقا حرفيا باللغة الانجليزية مع جميع الاوراق المطلوبة.\nسيُطلب من الطالب استكمال إجراءات التبصيم على الكروت الخاصة كجزء من متطلبات الحصول على الموافقة لتقديم امتحان الـ NCLEX، وفي حال كان الممرض خارج فلسطين، سيتم إرسال كروت التبصيم من قبلنا إلى الدولة التي يعمل بها الممرض، لضمان استكمال الإجراءات بالشكل الصحيح.', 'ar'),
(1, '2', 'خدماتنا - متابعة المعاملة والكورس', 'خدماتنا جلوبال جيت متابعة جميع ما يلي:\n1) ارسال جميع ما ذكر لشركة المعادلة الأمريكية.\n2) اخبارك بتقرير المعادلة وكشف علامات.\n3) كورس نكلكس متابعة وتقييم بشكل فردي وجماعي والذي يشمل ما يلي:\n- دورة الاستراتيجيات.\n- دورة احترافية تتضمن (12) استراتيجيات اساسية، بمجموع 12 ساعات تدريبية، تهدف الى تغيير نمط التفكير وتحسين مهارات تحليل الاسئلة والخيارات، بالاعتماد على 12 استراتيجية علمية معتمدة في اختبار NCLEX.\n- رسوم الدورة لغير المشتركين: 200 دينار أردني.\n- شرح المادة العلمية، الاستراتيجيات بشكل متسلسل واكاديمي.\n- تغطية شاملة لمحتوى امتحان NCLEX من خلال فيديوهات تعليمية منظمة، يمكن للمشترك الرجوع إليها في أي وقت، ما يتيح التعلم الذاتي وفق وتيرتك الخاصة.', 'ar'),
(1, '3', 'المتابعة الأكاديمية والتقييم', 'متابعة أكاديمية باستخدام حساب World-U وحساب GGHC وكلاهما بشكل مجاني.\n- تقديم تغذية راجعة دقيقة بعد كل مجموعة من الاسئلة بشكل فردي وجماعي.\n- تحليل أداء الطالب لتحديد نقاط القوة والضعف.\n- وضع خطة فردية لمعالجة الثغرات وتحسين المستوى.\n- مراجعة مفصلة بعد تقديم امتحانات الـ World-U لمراقبة التقدم وتوجيه التعلم بشكل مستمر.\n- خطة دراسية متكاملة وتحضير احترافي لامتحان NCLEX بورد نيو مكسيكو يدمج بين الدراسة الأكاديمية، المراجعة المكثفة، التقييم.\n- نقدم للممرضين برنامجا تدريبيا شاملا، من خلال الخطوات التالية:\n- مراجعة تحليلية متقدمة لأسئلة World-U, GGHC: بعد الانتهاء من دراسة بنك الأسئلة، يتم عقد جلسات مراجعة مركزة لأهم الأسئلة، مع مناقشة منهجية الحل والتفكير النقدي المناسب لكل نوع من الأسئلة.\n- جميع جلسات المراجعة تُسجل وتُحفظ على شكل فيديو ليتمكن المشترك من العودة إليها في أي وقت.\n- امتحانات تقييمية حصرية: يُقدم للمشترك امتحانات إلكترونية بشكل دوري اسبوعي لقياس الجاهزية قبل التقديم الرسمي. هذه الامتحانات مصممة خصيصا من قبل شركتنا، وتختلف عن اختبارات World-U، ولضمان تقييم موضوعي وفعال لمستوى الطالب.\n- ضمان النجاح من المحاولة الأولى: نقدم التزاما واضحا: نضمن نجاح المشترك من المحاولة الأولى، بشرط الالتزام الكامل بجميع التعليمات والخطة الدراسية. كما يتم إبلاغ الممرض بتقييم نسبة نجاحه قبل السفر لتقديم الامتحان.', 'ar'),
(1, '3', 'حجز الامتحان', 'حجز الامتحان: حسب رغبة الممرض حيث يكلف حجز امتحان النكلكس للمركز كما يلي:\n- أمريكا: مجانا.\n- تركيا: 177 دولار.\n- جنوب أفريقيا: 150 دولار.\n- الهند: 177 دولار.', 'ar'),
(1, '4', 'بعد الامتحان', 'بعد الامتحان على الطالب أن يجري ما يلي:\n- الفحص الطبي وإرسال التقرير لنا.\n- متابعة وحجز موعد في السفارة الأمريكية حسب الرغبة في عمان او القدس.\n- على الطالب أن يبدأ بالتحضير لامتحان PTE اللغة الانجليزية على أن يتم التواصل معنا شخصيا لتحديد موعده لانه صالح لمدة سنتين.', 'ar'),
(1, '4', 'الرسوم والأقساط', 'رسوم الخدمات 650 دينار وأقساط معاملة الانكلس يتم تقسيطهم على أربع دفعات حسب وضعك المالي كما يلي:\n1) معادلة الشهادة / تقرير اضافي لدائرة الهجرة / بريد: 400$ + 100$ ، و GGHC 150 JD.\n2) طلب مجلس التمريض نيو مكسيكو / التبصيم: 150$ + 44$ ، و GGHC 150 JD.\n3) تقرير ATT report إنه بقدر يقدم ويسجل للامتحان: 200$ ، و GGHC 150 JD.\n4) رسوم المركز الدولي حسب البلد ورغبة الطالب: 150$ - 177$ ، و GGHC 200 JD.\nUWORD; GHCC PLATFORM IS FREE', 'ar'),
(1, '5', 'بعد صدور الفيزا', 'بعد صدور الفيزا دور جلوبال جيت:\n1) التعاقد مع مشفى.\n2) حجز تذكرة طيران على حساب الشركة واستقبال في المطار.\n3) تأمين سكن خاص فيك الك وحدك لمدة 90 يوم.\n4) تأمين مبلغ 1000$ كمصروف شخصي لك خلال 90 يوم من وصولك للولاية.\n5) تدريبك في مختبر للتعرف على نظام الصحة الأمريكي لمدة 12-8 اسبوع مدفوع من الشركة مقابل 23$/hr تقريبا.\n6) عقد عمل لمدة 3744 hr يمكنك انهاءه حسب الرغبة بسنة او اكثر او اقل وبعدها يمكنك التعاقد مع نفس المشفى او مشفى آخر.\n7) نظام عمل الورديات في كل أمريكا: 12hr for 3 days each week.\nثمن كل ساعة عمل 42$-50$ تقريبا حسب الحد الأدنى للأجور في تلك الولاية.\nملاحظة:\n- الرجاء الاحتفاظ بأي وصل لأي مبلغ مدفوع لأنه مسترد من الشركة خلال 90 يوم من وصولك.\n- تلتزم الشركة بإرشادك لكل الأمور التي تخص المعاملات مثل رخصة السياقة والضمان الاجتماعي...الخ.', 'ar'),

(2, '1', 'عنوان العرض', 'WHO WE ARE?\nGlobal Gate Health Care\nNCLEX Program\nEmpowering Palestinian Nurses for U.S. Practice', 'en'),
(2, '2', 'شبكة التوجيه المهني', 'Our program features experienced Palestinian-American healthcare professionals who provide personalized guidance throughout the journey from preparation to U.S. practice.\n- Mr. Hesham Alsayyad, MSN, MBA, CPHQ, VA-BC, PMP – Lead NCLEX Instructor – California, USA.\n- Dr. Awni Dweekat, DNP, MSN, BSN, RN, CCRN – Cultural Transition and NCLEX Instructor – Ramallah, Palestine.\n- Dr. Fidaa Abu Ali, PhD, MPH, SON, BSN – Clinical expertise, Academic leadership, Digital innovation – Nablus, Palestine.', 'en'),
(2, '3', 'Mission & Vision', 'Our Mission:\nTo create sustainable pathways for qualified Palestinian nurses to build rewarding careers in the United States healthcare system while addressing critical nursing shortages and fostering cross-cultural healthcare excellence.\nTo empower Overseas Palestinian Nurses (OPN) by enhancing the affordability, security, and impact of their remittances, while fostering long-term economic development for Palestinian communities.\n\nOur Vision:\nA world where healthcare talent flows freely across borders, creating opportunities for Palestinian nurses while strengthening the U.S. healthcare system through diversity, cultural competence, and professional excellence.', 'en'),
(2, '4', 'Market Problem', 'Palestinian Nurse Market – The Challenge:\n- Limited career advancement opportunities in local healthcare system.\n- Significant wage gap compared to international markets.\n- Political instability affecting healthcare infrastructure.\n- High unemployment rate among qualified nursing graduates.\n- Complex barriers to international employment opportunities.\n\nU.S. Nursing Market – The Challenge:\n- Critical nursing shortage projected to reach 1.1 million by 2030.\n- Aging nursing workforce with 1/3 nearing retirement age.\n- Increasing healthcare demands from aging U.S. population.\n- Nursing schools unable to meet demand for new graduates.\n- High turnover rates and burnout among existing nursing staff.\n\nThe average age of registered nurses (RNs) in the United States is approximately 43.4 years. Over 600,000 RNs expected to retire by 2030. Health Resources and Services Administration (HRSA, 2024). Bureau of Health Workforce.\nAs of 2024, approximately 101,000 people in the United States are aged 100 or older, reaching around 422,000 by 2054.', 'en'),
(2, '5', 'Palestinian Nurse Market Overview', 'Palestinian nursing education produces 2000+ graduates annually.\nLocal healthcare system can only absorb 40% of new graduates.\nAverage nurse salary: $800-1,200/month.\nA nationwide WHO-led survey across the West Bank (including East Jerusalem) and Gaza Strip reports over 25,211 nurses in total.\nActive–Employed 14,593 out of 25,211.\n85% Nurses Interested in International Opportunities.\n40% Unemployment Rate Among Recent Nursing Graduates.\nPalestinian Central Bureau of statistics (PCBS) Labour-Force Survey, 2021.', 'en'),
(2, '6', 'U.S. Nursing Market Overview', 'The U.S. nursing market faces a critical shortage that continues to grow annually, creating significant opportunities for qualified international nurses.\nProjected shortage of 1.1 million nurses by 2030.\nAverage annual salary: $80,000 - $120,000+.\nThere were approximately 22 million healthcare workers in the USA, among them 4.7 million RN’S (CDC, AACN, 2025).\nInternational nurses make up about 15% of the nursing workforce.\n33% Nurses Nearing Retirement.', 'en'),
(2, '7-9', 'Our Solution and Strategic Collaborations', 'We propose the establishment of Global Gate Health Care.\nThis venture aims:\n- To bridge the critical healthcare staffing gap in the U.S. by providing highly trained nurses.\n- To empower overseas Palestinian nurses (OPN) to enhance economic development for Palestinian communities.\n\nStrategic Collaborations:\nAcademic Partnership:\n1- Palestinian nursing council - Palestine.\n2- Bier Ziet University – Palestine.\n3- UWarld (Technology partner) – USA.\nHealthcare Partner:\n1- WWSS (Westways Staffing Services) – USA.\n   - Healthcare Employment Network.\n   - U.S. State Department (Government relation).\n\nGlobal gate in collaboration with Bier Ziet university proposes the development and delivery of missing or insufficient coursework to address curriculum gaps identified by the U.S. state boards of nursing.\n\nHealthcare Partners:\n- American Hospital Association.\n- Healthcare Employment Network through WWSS.\nEducational Partners:\n- Palestinian Nursing Council – Credential Verification.\nGovernment Relations:\n- U.S. State Department – Healthcare Workforce Initiative through WWSS.\nTechnology Partners:\n- UWarld – Digital Learning Platform – Provides customized e-learning platform with NCLEX simulation technology.\n\nWestways Staffing Services, Inc. is a nurse-owned healthcare staffing agency founded in 1992 by Harold Sterling, R.N., who serves as the company''s CEO. With over 30 years of experience, Westways specializes in per diem and travel nursing, as well as staffing for cardiac catheterization labs, allied healthcare, and pharmacy roles across the United States.', 'en'),
(2, '10', 'What is NCLEX and fee breakdown', 'What is NCLEX:\nThe NCLEX-RN (National Council Licensure Examination for Registered Nurses) is a standardized exam required to practice as an RN in the USA and Canada.\nComputerized Adaptive Testing (CAT): The test adapts to your ability level. Questions get harder or easier based on your previous answers.\nLength: NCLEX-RN: 85–150 questions.\nMaximum time: 5 hours.\nPTE is an English proficiency test.\nCGFNS (Commission on Graduate of Foreign Nursing School).\nRetaking the NCLEX:\nIf you fail, you can retake it after 45 days (varies by state).\nYou can take it up to 8 times/year.\n\nFee Breakdown for International RN Applicants:\n- Credential Evaluation service (CES) (4 weeks): $400 (R) / 150 JOD for GGH (R).\n- Account with Josph and Silny as Administrator.\n- Application Fee (NMBON): $150 (R).\n- Fingerprinting / Background Check: $44 (R).\n- ATT eligibility Pearson VUE (2-3 weeks): $200 (R) / 150 JOD for GGH (R).\n- NCLEX Review Course (Uworld 3 months): $0 / 150 JOD for GGH (R).\n- Schedule NCLEX exam: 200 JOD for GGH (R).\n- International test center surcharge: $150 (R).\n- Mailing from Palestine to USA: $100 (R).\nAfter Passing the NECLEX:\n- Immigration Medical exam: $300 (You – Refundable).\n- U.S. Visa interview: $325 (You – Refundable).\n- English proficiency exam (PTE): $300 (You – Refundable).\nImmigration and Licensing fees:\n- NMBON License Issuance Fee: $110 (WWSS).\n- VisaScreen Certificate: $655 (WWSS).\n- Immigration services: $15000 (WWSS).\nRelocation:\n- One way Airfare to the U.S.: $800 (WWSS).\n- Upon arrival the U.S. pocket money $1000 (WWSS).\n- Up to 3 months accommodation by (WWSS).', 'en'),
(2, '10', 'Global Gate Mentorship and contacts', 'Global Gate Mentorship:\n- Cultural Bridge: Share values of compassion, resilience, and family in the U.S. healthcare system.\n- Support Circles: Emotional and social support during your transition to life and work abroad.\n- Learning Support: Adapt to new systems without fear everyone starts somewhere.\n- Continuing Education & Certification: Help with applying for U.S. certifications (e.g., CCRN, NP, PA, CRNA, DNP).\n- Leadership Professional Development: As charge nurse etc.\n- Understanding U.S. Cultural Norms: Food & religion, privacy, gender, self help.\n- Choose a workplace that truly values you: Competitive salary, Sign-on bonuses, Sponsorship for advanced education, Work-life balance, Pension plan, Saving plan, Health insurance.\n- Confidence in Social Settings: Overcome fear of being judged for your accent, background, or customs.\n\nContact Information:\nChief Executive Officer: Dr. Fidaa` S. Ali, +972599440492, ceo@globalgatehealthcare.com.\nGeneral Manager: Dr.Awni Dweekat, +1 9512556278, +972595161964, manager@globalgatehealthcare.com.\nChief Administrative Officer: Mr. Hesham AlSayyad, +1(714)467-5467, cao@globalgatehealthcare.com.\nOUR OFICESS:\nUSA Office: 3944, Satsuma lane, Corona CA, 92883, USA. Tel: +1(714)467-5467.\nPalestine Office: Ramallah, Palestine, Manarah Building, 9th Floor, Makani Hub. Tel: +972595161964.', 'en');

INSERT INTO `faq_items` (`question`, `answer`, `source_file_id`, `source_page`, `section_name`, `language_code`) VALUES
('ما هي الوثائق المطلوبة للتقديم؟', 'الوثائق المطلوبة هي: صورة عن جواز السفر ساري المفعول، كشف الثانوية العامة باللغة الإنجليزية، مغلف كشف علامات الشهادة الجامعية مع المصدقة من القبول والتسجيل مختوم، مغلف من قسم التمريض فيه وصف المساقات ونموذج مختوم يصف عدد الساعات النظرية والعملية لكل مادة تخصصية، ومغلف النقابة ويشمل حسن سير وسلوك، عضوية النقابة، ونموذج النقابة موقع من عطوفة النقيب باللغة الإنجليزية. يجب أن يكون الاسم مطابقا حرفيا باللغة الإنجليزية مع جميع الأوراق المطلوبة.', 1, '2', 'الوثائق المطلوبة', 'ar'),
('هل يشترط أن يكون الاسم مطابقا لجواز السفر؟', 'نعم. يجب أن يكون الاسم في جواز السفر الساري المفعول مطابقا حرفيا باللغة الإنجليزية مع جميع الأوراق المطلوبة، وأن يكون جواز السفر ساري المفعول على الأقل لمدة سنتين.', 1, '2', 'الوثائق المطلوبة', 'ar'),
('هل يوجد تبصيم؟', 'نعم. سيُطلب من الطالب استكمال إجراءات التبصيم على الكروت الخاصة كجزء من متطلبات الحصول على الموافقة لتقديم امتحان الـ NCLEX، وإذا كان الممرض خارج فلسطين سيتم إرسال كروت التبصيم إلى الدولة التي يعمل بها الممرض.', 1, '2', 'الوثائق المطلوبة', 'ar'),
('ماذا تشمل خدمات جلوبال جيت؟', 'تشمل الخدمات: إرسال جميع ما ذكر لشركة المعادلة الأمريكية، إخبارك بتقرير المعادلة وكشف العلامات، وكورس نكلكس مع متابعة وتقييم بشكل فردي وجماعي.', 1, '2', 'خدماتنا - متابعة المعاملة والكورس', 'ar'),
('ما هي دورة الاستراتيجيات؟', 'هي دورة احترافية تتضمن 12 استراتيجيات أساسية، بمجموع 12 ساعات تدريبية، وتهدف إلى تغيير نمط التفكير وتحسين مهارات تحليل الأسئلة والخيارات بالاعتماد على 12 استراتيجية علمية معتمدة في اختبار NCLEX.', 1, '2', 'خدماتنا - متابعة المعاملة والكورس', 'ar'),
('كم رسوم دورة الاستراتيجيات لغير المشتركين؟', 'رسوم الدورة لغير المشتركين هي 200 دينار أردني.', 1, '2', 'خدماتنا - متابعة المعاملة والكورس', 'ar'),
('هل يوجد حسابات مجانية للمتابعة الأكاديمية؟', 'نعم. المتابعة الأكاديمية تكون باستخدام حساب World-U وحساب GGHC وكلاهما بشكل مجاني.', 1, '3', 'المتابعة الأكاديمية والتقييم', 'ar'),
('هل توجد امتحانات تقييمية؟', 'نعم. يُقدم للمشترك امتحانات إلكترونية بشكل دوري أسبوعي لقياس الجاهزية قبل التقديم الرسمي، وهي مصممة خصيصا من قبل الشركة وتختلف عن اختبارات World-U.', 1, '3', 'المتابعة الأكاديمية والتقييم', 'ar'),
('هل تضمنون النجاح من المحاولة الأولى؟', 'نعم، ورد في الملف: نضمن نجاح المشترك من المحاولة الأولى، بشرط الالتزام الكامل بجميع التعليمات والخطة الدراسية، كما يتم إبلاغ الممرض بتقييم نسبة نجاحه قبل السفر لتقديم الامتحان.', 1, '3', 'المتابعة الأكاديمية والتقييم', 'ar'),
('أين يمكن حجز الامتحان وكم التكلفة؟', 'حسب رغبة الممرض: أمريكا مجانا، تركيا 177 دولار، جنوب أفريقيا 150 دولار، الهند 177 دولار.', 1, '3', 'حجز الامتحان', 'ar'),
('ماذا يجب على الطالب بعد الامتحان؟', 'بعد الامتحان على الطالب أن يجري ما يلي: الفحص الطبي وإرسال التقرير، متابعة وحجز موعد في السفارة الأمريكية حسب الرغبة في عمان أو القدس، والبدء بالتحضير لامتحان PTE اللغة الإنجليزية مع التواصل شخصيا لتحديد موعده.', 1, '4', 'بعد الامتحان', 'ar'),
('كم رسوم الخدمات؟', 'رسوم الخدمات هي 650 دينار، وأقساط معاملة الانكلس يتم تقسيطهم على أربع دفعات حسب الوضع المالي.', 1, '4', 'الرسوم والأقساط', 'ar'),
('ما هي الدفعة الأولى؟', 'الدفعة الأولى تشمل: معادلة الشهادة، تقرير إضافي لدائرة الهجرة، والبريد. الرسوم المذكورة: 400$ + 100$ ، و GGHC 150 JD.', 1, '4', 'الرسوم والأقساط', 'ar'),
('ما هي الدفعة الثانية؟', 'الدفعة الثانية تشمل: طلب مجلس التمريض نيو مكسيكو والتبصيم. الرسوم المذكورة: 150$ + 44$ ، و GGHC 150 JD.', 1, '4', 'الرسوم والأقساط', 'ar'),
('ما هي الدفعة الثالثة؟', 'الدفعة الثالثة تشمل: تقرير ATT report إنه بقدر يقدم ويسجل للامتحان. الرسوم المذكورة: 200$ ، و GGHC 150 JD.', 1, '4', 'الرسوم والأقساط', 'ar'),
('ما هي الدفعة الرابعة؟', 'الدفعة الرابعة تشمل: رسوم المركز الدولي حسب البلد ورغبة الطالب. الرسوم المذكورة: 150$ - 177$ ، و GGHC 200 JD.', 1, '4', 'الرسوم والأقساط', 'ar'),
('ماذا تقدم جلوبال جيت بعد صدور الفيزا؟', 'بعد صدور الفيزا: التعاقد مع مشفى، حجز تذكرة طيران على حساب الشركة واستقبال في المطار، تأمين سكن خاص لمدة 90 يوم، تأمين مبلغ 1000$ كمصروف شخصي خلال 90 يوم من الوصول، تدريب في مختبر للتعرف على نظام الصحة الأمريكي لمدة 12-8 أسبوع مدفوع من الشركة، وعقد عمل لمدة 3744 ساعة.', 1, '5', 'بعد صدور الفيزا', 'ar'),
('كم عدد ساعات العمل الأسبوعية المذكورة؟', 'نظام عمل الورديات المذكور هو 12 ساعة لثلاثة أيام كل أسبوع.', 1, '5', 'بعد صدور الفيزا', 'ar'),
('كم أجر الساعة المذكور؟', 'ثمن كل ساعة عمل 42$-50$ تقريبا حسب الحد الأدنى للأجور في تلك الولاية.', 1, '5', 'بعد صدور الفيزا', 'ar'),
('هل يجب الاحتفاظ بالإيصالات؟', 'نعم. وردت ملاحظة بضرورة الاحتفاظ بأي وصل لأي مبلغ مدفوع لأنه مسترد من الشركة خلال 90 يوم من الوصول.', 1, '5', 'بعد صدور الفيزا', 'ar'),

('What is NCLEX-RN?', 'The NCLEX-RN is a standardized exam required to practice as an RN in the USA and Canada.', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('How many questions are in NCLEX-RN?', 'NCLEX-RN length is 85–150 questions, with a maximum time of 5 hours.', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('Can the NCLEX be retaken?', 'Yes. If you fail, you can retake it after 45 days (varies by state), and you can take it up to 8 times per year.', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('What is the CES fee?', 'Credential Evaluation Service (CES) is listed as $400 (R), with 150 JOD for GGH (R).', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('What is the fingerprinting fee?', 'Fingerprinting / Background Check is listed as $44 (R).', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('What is the ATT eligibility fee?', 'ATT eligibility Pearson VUE (2-3 weeks) is listed as $200 (R), with 150 JOD for GGH (R).', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('What is the international test center surcharge?', 'The international test center surcharge is listed as $150 (R).', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('What is the mailing cost from Palestine to USA?', 'Mailing from Palestine to USA is listed as $100 (R).', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('What are the post-passing refundable costs?', 'After passing the NECLEX, the listed refundable costs are: Immigration Medical exam $300, U.S. Visa interview $325, and English proficiency exam (PTE) $300.', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('What relocation support is listed?', 'The listed relocation support includes one way airfare to the U.S. $800 (WWSS), pocket money $1000 (WWSS), and up to 3 months accommodation by WWSS.', 2, '10', 'What is NCLEX and fee breakdown', 'en'),
('Who are the main contacts?', 'Chief Executive Officer: Dr. Fidaa` S. Ali. General Manager: Dr.Awni Dweekat. Chief Administrative Officer: Mr. Hesham AlSayyad.', 2, '10', 'Global Gate Mentorship and contacts', 'en');

SET FOREIGN_KEY_CHECKS = 1;
