import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      // General
      'app_name': 'Rento Go',
      'search': 'بحث',
      'search_hint': 'ابحث مدينة أو منطقة...',
      'filter': 'فلترة',
      'all': 'الكل',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'close': 'إغلاق',
      'confirm': 'تأكيد',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'retry': 'إعادة المحاولة',
      'no_results': 'لا توجد نتائج',

      // Tabs
      'properties': 'عقارات',
      'cars': 'سيارات',

      // Bottom Navigation
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'messages': 'المحادثات',
      'my_listings': 'إعلاناتي',
      'profile': 'حسابي',

      // Property Types
      'apartments': 'شقق',
      'villas_chalets': 'فلل وشاليهات',
      'shops_offices': 'محلات ومكاتب',
      'student_housing': 'سكن طلاب',
      'lands': 'أراضي',

      // Car Types
      'daily_use': 'استخدام يومي',
      'wedding': 'زفة أعراس',
      'tourism': 'سياحية',

      // CTA Banner
      'advertise_now': 'أعلن الآن',
      'add_highlight_property': 'ضف وأبرز عقارك',
      'add_highlight_car': 'ضف وأبرز سيارتك',
      'add_property': 'أضف عقارات',
      'add_car': 'أضف سيارات',
      'add_listing_button': 'أضف عقارك أو سيارتك',

      // Listing Details
      'for_rent': 'للإيجار',
      'price': 'السعر',
      'negotiable': 'قابل للتفاوض',
      'area': 'المساحة',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'floor': 'الطابق',
      'description': 'الوصف',
      'contact': 'تواصل',
      'call': 'اتصال',
      'whatsapp': 'واتساب',
      'report': 'إبلاغ',

      // Car Details
      'model': 'الموديل',
      'gearbox': 'ناقل الحركة',
      'automatic': 'أوتوماتيك',
      'manual': 'عادي',
      'with_driver': 'مع سائق',
      'without_driver': 'بدون سائق',
      'plate_color': 'لون اللوحة',
      'yellow_plate': 'أصفر',
      'white_plate': 'أبيض',

      // Auth
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'logout': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'phone': 'رقم الهاتف',
      'name': 'الاسم',
      'edit_name': 'تعديل الاسم',
      'edit_profile': 'تعديل الملف الشخصي',
      'name_required': 'الاسم مطلوب',
      'name_too_short': 'الاسم قصير جداً',
      'name_updated_successfully': 'تم تحديث الاسم بنجاح',
      'profile_updated_successfully': 'تم تحديث الملف الشخصي بنجاح',
      'update_failed': 'فشل التحديث',
      'security_settings': 'إعدادات الأمان',
      'change_password': 'تغيير كلمة المرور',
      'change_email': 'تغيير البريد الإلكتروني',
      'change_phone': 'تغيير رقم الهاتف',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'new_email': 'البريد الإلكتروني الجديد',
      'new_phone': 'رقم الهاتف الجديد',
      'password_changed_successfully': 'تم تغيير كلمة المرور بنجاح',
      'email_changed_successfully': 'تم تغيير البريد الإلكتروني بنجاح',
      'phone_changed_successfully': 'تم تغيير رقم الهاتف بنجاح',
      'password_too_short': 'كلمة المرور قصيرة جداً',
      'invalid_phone': 'رقم الهاتف غير صالح',
      'required': 'مطلوب',
      'company_name': 'اسم الشركة',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'already_have_account': 'لديك حساب بالفعل؟',
      'login_subtitle': 'سجّل دخولك للمتابعة',
      'create_account': 'إنشاء حساب جديد',
      'register_subtitle': 'أنشئ حسابك للبدء',
      'full_name': 'الاسم الكامل',
      'user_type': 'نوع الحساب',
      'confirm_password': 'تأكيد كلمة المرور',
      'required_field': 'هذا الحقل مطلوب',
      'password_min_length': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'passwords_not_match': 'كلمتا المرور غير متطابقتين',
      'invalid_email': 'البريد الإلكتروني غير صالح',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب؟',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'forgot_password_subtitle': 'أدخل رقم هاتفك لإرسال رمز التحقق',
      'send_code': 'إرسال الرمز',
      'verify_code': 'التحقق من الرمز',
      'enter_otp': 'أدخل رمز التحقق',
      'code_sent_to': 'تم إرسال الرمز إلى',
      'enter_complete_code': 'أدخل الرمز كاملاً',
      'verify': 'تحقق',
      'didnt_receive_code': 'لم تستلم الرمز؟',
      'resend': 'إعادة الإرسال',
      'code_resent': 'تم إعادة إرسال الرمز',
      'phone_verified': 'تم التحقق من رقم الهاتف',
      'password_reset_success': 'تم إعادة تعيين كلمة المرور بنجاح',

      // User Types
      'renter': 'مستأجر',
      'owner': 'مالك',
      'office': 'مكتب عقارات',
      'car_lessor': 'مؤجر سيارات',

      // Status
      'pending_review': 'بانتظار المراجعة',
      'active': 'نشط',
      'rejected': 'مرفوض',
      'expired': 'منتهي',
      'paused': 'متوقف',

      // Plans
      'select_plan': 'اختر باقة',
      'monthly': 'شهري',
      'single_ad': 'إعلان واحد',
      'package': 'باقة',
      'unlimited': 'غير محدود',
      'listings': 'إعلانات',
      'subscribe': 'اشترك',

      // Settings
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'dark_mode': 'الوضع الداكن',
      'notifications': 'الإشعارات',
      'privacy_policy': 'سياسة الخصوصية',
      'terms': 'الشروط والأحكام',
      'about': 'عن التطبيق',

      // Messages
      'listing_created': 'تم إنشاء الإعلان بنجاح',
      'listing_updated': 'تم تحديث الإعلان',
      'added_to_favorites': 'تمت الإضافة للمفضلة',
      'removed_from_favorites': 'تمت الإزالة من المفضلة',
      'report_submitted': 'تم إرسال البلاغ',

      // Add Listing Form
      'add_new_listing': 'إضافة إعلان جديد',
      'listing_type': 'نوع الإعلان',
      'property_type': 'نوع العقار',
      'car_usage_type': 'نوع الاستخدام',
      'title': 'العنوان',
      'title_hint': 'أدخل عنوان الإعلان',
      'price_hint': 'أدخل السعر',
      'area_hint': 'أدخل المساحة بالمتر',
      'select_region': 'اختر المنطقة',
      'select_city': 'اختر المدينة',
      'region': 'المنطقة',
      'city': 'المدينة',
      'select_location_required': 'يجب اختيار المنطقة والمدينة',
      'agree_to': 'أوافق على ',
      'terms_of_service': 'شروط الاستخدام',
      'delete_account': 'حذف الحساب',
      'delete_account_confirm':
          'هل أنت متأكد من حذف حسابك؟ سيتم حذف جميع بياناتك نهائياً.',
      'enter_password_to_confirm': 'أدخل كلمة المرور للتأكيد',
      'account_deleted': 'تم حذف الحساب بنجاح',
      'error_loading': 'خطأ في التحميل',
      'address': 'العنوان',
      'address_hint': 'أدخل العنوان بالتفصيل',
      'description_hint': 'أدخل وصف تفصيلي',
      'contact_phone': 'رقم التواصل',
      'whatsapp_number': 'رقم الواتساب',
      'add_images': 'إضافة صور',
      'select_images': 'اختر الصور',
      'max_images': 'الحد الأقصى 10 صور',
      'submit_listing': 'نشر الإعلان',
      'brand': 'الشركة المصنعة',
      'year': 'السنة',
      'color': 'اللون',
      'seats': 'المقاعد',
      'daily_price': 'السعر اليومي',
      'weekly_price': 'السعر الأسبوعي',
      'monthly_price': 'السعر الشهري',

      // Add Listing - Additional
      'apartment': 'شقة',
      'villa_chalet': 'فيلا / شاليه',
      'shop_office': 'محل / مكتب',
      'land': 'أرض',
      'bathrooms_label': 'الحمامات',
      'floor_label': 'الطابق',
      'brand_label': 'الماركة',
      'model_label': 'الموديل',
      'year_label': 'سنة الصنع',
      'gearbox_label': 'ناقل الحركة',
      'plate_color_label': 'لون اللوحة',
      'yellow': 'أصفر',
      'white': 'أبيض',
      'green': 'أخضر',
      'price_label': 'السعر (شيكل)',
      'description_label': 'الوصف',
      'contact_phone_label': 'رقم التواصل',
      'whatsapp_label': 'واتساب',
      'free': 'مجاني',
      'contact_us': 'تواصل معنا',
      'whatsapp_support': 'دعم واتساب',

      // Welcome Bonus
      'welcome_title': 'مرحباً بك! 🎉',
      'welcome_bonus_title': 'حصلت على باقة ترحيبية مجانية!',
      'welcome_bonus_desc':
          'يمكنك الآن إضافة إعلان واحد مجاناً.\nاستمتع بتجربة التطبيق!',
      'start_now': 'ابدأ الآن',

      // Car Pricing
      'enter_one_price': 'أدخل سعر واحد على الأقل',
      'daily': 'يومي',
      'weekly': 'أسبوعي',
      'rental_prices': 'أسعار التأجير',

      // Profile Screen - Subscriptions
      'my_active_subscriptions': 'باقاتي الفعالة',
      'view_all': 'عرض الكل',
      'no_active_subscriptions': 'لا توجد باقات فعالة',
      'real_estate': 'عقارات',
      'vehicles': 'سيارات',
      'listings_remaining': 'متبقي',
      'listing_unit': 'إعلان',
      'days_remaining': 'متبقي',
      'day_unit': 'يوم',

      // My Subscriptions Screen
      'my_subscriptions': 'باقاتي',
      'active_tab': 'فعالة',
      'pending_tab': 'معلقة',
      'history_tab': 'منتهية',
      'no_pending_subscriptions': 'لا توجد باقات معلقة',
      'no_expired_subscriptions': 'لا توجد باقات منتهية',
      'general': 'عام',
      'pending_approval': 'بانتظار الموافقة',
      'status_rejected': 'مرفوض',
      'status_expired': 'منتهية',
      'status_cancelled': 'ملغاة',
      'status_active': 'فعالة',
      'listings_label': 'الإعلانات',
      'days_remaining_label': 'الأيام المتبقية',
      'expiry_date': 'تاريخ الانتهاء',
      'subscription_date': 'تاريخ الاشتراك',

      // Checkout Screen
      'choose_package': 'اختر باقة',
      'failed_load_packages': 'فشل تحميل الباقات',
      'please_enter_sender_name': 'الرجاء إدخال اسم المُحوِل',
      'pending_verification': 'في انتظار التحقق',
      'transfer_received':
          'تم استلام بيانات الحوالة. سيتم التحقق وتفعيل الباقة خلال 24 ساعة.',
      'purchase_success': 'تم شراء الباقة بنجاح!',
      'package_activated': 'تم تفعيل الباقة في حسابك',
      'ok': 'حسناً',
      'purchase_failed': 'فشل شراء الباقة',
      'unknown_error': 'خطأ غير معروف',
      'network_error': 'خطأ في الاتصال',
      'no_packages_available': 'لا توجد باقات متاحة',
      'swipe_to_see_more': 'اسحب لرؤية المزيد',
      'unlimited_listings': 'إعلانات غير محدودة',
      'listings_count': 'إعلان',
      'days_validity': 'يوم صلاحية',
      'featured_listing': 'إعلان مميز',
      'region_notifications': 'إشعارات المنطقة',
      'city_notifications': 'إشعارات المدينة',
      'trusted_advertiser': 'معلن موثوق',
      'subscribe_now': 'اشترك الآن',
      'payment_method': 'طريقة الدفع',
      'bank_transfer': 'حوالة بنكية',
      'transfer_to_bank': 'حوّل إلى حسابنا البنكي',
      'fast_secure_payment': 'دفع سريع وآمن',
      'test_payment': 'دفع تجريبي',
      'test_only': 'للاختبار فقط',
      'bank_name': 'البنك',
      'account_name': 'الحساب',
      'account_number': 'رقم الحساب',
      'sender_name': 'اسم المُحوِل',
      'confirm_and_pay': 'تأكيد والدفع',
      'test_mode_notice': 'وضع تجريبي - الدفع غير حقيقي',

      // Search Screen
      'filters': 'الفلاتر',
      'reset': 'إعادة تعيين',
      'all_regions': 'كل المناطق',
      'all_cities': 'كل المدن',
      'min_price': 'أقل سعر',
      'max_price': 'أعلى سعر',
      'min_bedrooms': 'أقل غرف',
      'min_area': 'أقل مساحة',
      'search_results': 'نتائج البحث',

      // Add Listing Screen
      'add_property_title': 'إضافة عقار',
      'add_car_title': 'إضافة سيارة',
      'select_payment_or_package': 'يرجى اختيار خيار دفع أو شراء باقة',
      'listing_added_success': 'تم إضافة الإعلان بنجاح!',
      'listing_under_review':
          'إعلانك الآن قيد المراجعة من قبل فريقنا.\nسيصلك إشعار عند قبول الإعلان وعرضه.',
      'active_subscription': 'اشتراك فعال',
      'review_notice': 'سيتم مراجعة إعلانك من قبل الإدارة قبل نشره',
      'publish_listing': 'نشر الإعلان',
      'property_type_label': 'نوع العقار *',
      'title_label': 'العنوان',
      'title_example': 'مثال: شقة فاخرة للإيجار',
      'bedrooms_form': 'غرف النوم',
      'area_form': 'المساحة (م²)',
      'floor_form': 'الطابق',
      'brand_required': 'الماركة *',
      'brand_example': 'مثال: تويوتا',
      'model_required': 'الموديل *',
      'model_example': 'مثال: كامري',
      'year_required': 'سنة الصنع *',
      'with_driver_label': 'مع سائق',
      'price_required': 'السعر (شيكل) *',
      'daily_price_label': 'سعر اليوم',
      'weekly_price_label': 'سعر الأسبوع',
      'monthly_price_label': 'سعر الشهر',
      'contact_phone_required': 'رقم التواصل *',
      'whatsapp_optional': 'واتساب (اختياري)',
      'description_optional': 'الوصف (اختياري)',
      'description_placeholder': 'أضف وصفاً لإعلانك...',
      'photos': 'الصور',
      'add_photos': 'إضافة صور',
      'payment_options': 'خيارات الدفع',

      // Edit Listing Screen
      'edit_property': 'تعديل العقار',
      'edit_car': 'تعديل السيارة',
      'rejection_reason': 'سبب الرفض:',
      'edit_and_resubmit': 'عدّل الإعلان وأرسله مرة أخرى للمراجعة',
      'resubmit_for_review': 'إرسال للمراجعة مجدداً',
      'listing_sent_for_review': 'تم إرسال الإعلان للمراجعة!',

      // Chat Screen
      'message_failed': 'فشل إرسال الرسالة',
      'start_conversation': 'ابدأ المحادثة',
      'send_message_to': 'أرسل رسالة للتواصل مع',
      'type_message': 'اكتب رسالة...',
      'no_conversations': 'لا توجد محادثات',
      'no_conversations_hint': 'ابدأ محادثة من صفحة الإعلان',
      'terms_conditions': 'الشروط والأحكام',
      'user': 'مستخدم',
      'now': 'الآن',

      // Auth (feature 002) — error reasons + user-type labels.
      // See specs/002-auth-login-register/research.md § R-005.
      'auth_error_invalid_credentials': 'رقم الهاتف أو كلمة المرور غير صحيحة',
      'auth_error_account_pending': 'حسابك قيد المراجعة من قبل الإدارة',
      'auth_error_account_blocked': 'تم حظر حسابك',
      'auth_error_email_exists': 'البريد الإلكتروني مستخدم مسبقاً',
      'auth_error_phone_exists': 'رقم الهاتف مستخدم مسبقاً',
      'auth_error_invalid_email': 'البريد الإلكتروني غير صالح',
      'auth_error_invalid_phone': 'رقم الهاتف غير صالح',
      'auth_error_weak_password': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'auth_error_missing_fields': 'يرجى إدخال جميع الحقول المطلوبة',
      'auth_error_validation_failed': 'يرجى التحقق من البيانات المدخلة',
      'auth_error_network': 'فشل الاتصال بالخادم',
      'auth_error_unknown_login': 'فشل تسجيل الدخول',
      'auth_error_unknown_register': 'فشل التسجيل',
      'auth_error_invalid_otp': 'رمز التحقق غير صحيح',
      'auth_error_expired_otp': 'انتهت صلاحية رمز التحقق',
      'user_type_renter': 'مستأجر',
      'user_type_owner': 'مالك عقار',
      'user_type_office': 'مكتب عقارات',
      'user_type_car_lessor': 'مؤجر سيارات',
      'must_accept_terms': 'يجب الموافقة على الشروط والأحكام',
      'account_under_review': 'حسابك قيد المراجعة',
      'verification_required': 'يتطلب التحقق',
      'verification_required_body': 'يرجى التحقق من بريدك الإلكتروني أو هاتفك',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'agree_to_terms_prefix': 'أوافق على ',
    },
    'he': {
      // General
      'app_name': 'Rento Go',
      'search': 'חיפוש',
      'search_hint': 'חפש עיר או אזור...',
      'filter': 'סינון',
      'all': 'הכל',
      'save': 'שמור',
      'cancel': 'ביטול',
      'delete': 'מחק',
      'edit': 'עריכה',
      'add': 'הוסף',
      'close': 'סגור',
      'confirm': 'אישור',
      'loading': 'טוען...',
      'error': 'שגיאה',
      'success': 'הצלחה',
      'retry': 'נסה שוב',
      'no_results': 'אין תוצאות',

      // Tabs
      'properties': 'נכסים',
      'cars': 'רכבים',

      // Bottom Navigation
      'home': 'בית',
      'favorites': 'מועדפים',
      'messages': 'הודעות',
      'my_listings': 'המודעות שלי',
      'profile': 'פרופיל',

      // Property Types
      'apartments': 'דירות',
      'villas_chalets': 'וילות ושאלות',
      'shops_offices': 'חנויות ומשרדים',
      'student_housing': 'דיור לסטודנטים',
      'lands': 'קרקעות',

      // Car Types
      'daily_use': 'שימוש יומי',
      'wedding': 'חתונות',
      'tourism': 'תיירות',

      // CTA Banner
      'advertise_now': 'פרסם עכשיו',
      'add_highlight_property': 'הוסף והדגש את הנכס שלך',
      'add_highlight_car': 'הוסף והדגש את הרכב שלך',
      'add_property': 'הוסף נכסים',
      'add_car': 'הוסף רכבים',
      'add_listing_button': 'הוסף נכס או רכב',

      // Listing Details
      'for_rent': 'להשכרה',
      'price': 'מחיר',
      'negotiable': 'ניתן למשא ומתן',
      'area': 'שטח',
      'bedrooms': 'חדרי שינה',
      'bathrooms': 'חדרי אמבטיה',
      'floor': 'קומה',
      'description': 'תיאור',
      'contact': 'צור קשר',
      'call': 'התקשר',
      'whatsapp': 'וואטסאפ',
      'report': 'דווח',

      // Car Details
      'model': 'דגם',
      'gearbox': 'תיבת הילוכים',
      'automatic': 'אוטומטי',
      'manual': 'ידני',
      'with_driver': 'עם נהג',
      'without_driver': 'ללא נהג',
      'plate_color': 'צבע לוחית',
      'yellow_plate': 'צהוב',
      'white_plate': 'לבן',

      // Auth
      'login': 'התחברות',
      'register': 'הרשמה',
      'logout': 'התנתק',
      'email': 'אימייל',
      'password': 'סיסמה',
      'phone': 'טלפון',
      'name': 'שם',
      'edit_name': 'עריכת שם',
      'edit_profile': 'עריכת פרופיל',
      'name_required': 'שם נדרש',
      'name_too_short': 'השם קצר מדי',
      'name_updated_successfully': 'השם עודכן בהצלחה',
      'profile_updated_successfully': 'הפרופיל עודכן בהצלחה',
      'update_failed': 'העדכון נכשל',
      'security_settings': 'הגדרות אבטחה',
      'change_password': 'שינוי סיסמה',
      'change_email': 'שינוי אימייל',
      'change_phone': 'שינוי טלפון',
      'current_password': 'סיסמה נוכחית',
      'new_password': 'סיסמה חדשה',
      'new_email': 'אימייל חדש',
      'new_phone': 'טלפון חדש',
      'password_changed_successfully': 'הסיסמה שונתה בהצלחה',
      'email_changed_successfully': 'האימייל שונה בהצלחה',
      'phone_changed_successfully': 'הטלפון שונה בהצלחה',
      'password_too_short': 'הסיסמה קצרה מדי',
      'invalid_phone': 'מספר טלפון לא תקין',
      'required': 'נדרש',
      'company_name': 'שם החברה',
      'forgot_password': 'שכחת סיסמה?',
      'dont_have_account': 'אין לך חשבון?',
      'already_have_account': 'כבר יש לך חשבון?',
      'login_subtitle': 'התחבר כדי להמשיך',
      'create_account': 'צור חשבון חדש',
      'register_subtitle': 'צור חשבון כדי להתחיל',
      'full_name': 'שם מלא',
      'user_type': 'סוג חשבון',
      'confirm_password': 'אשר סיסמה',
      'required_field': 'שדה חובה',
      'password_min_length': 'הסיסמה חייבת להכיל לפחות 6 תווים',
      'passwords_not_match': 'הסיסמאות לא תואמות',
      'invalid_email': 'אימייל לא תקין',
      'no_account': 'אין לך חשבון?',
      'have_account': 'יש לך חשבון?',
      'reset_password': 'איפוס סיסמה',
      'forgot_password_subtitle': 'הזן את מספר הטלפון שלך לשליחת קוד אימות',
      'send_code': 'שלח קוד',
      'verify_code': 'אמת קוד',
      'enter_otp': 'הזן קוד אימות',
      'code_sent_to': 'הקוד נשלח אל',
      'enter_complete_code': 'הזן את הקוד המלא',
      'verify': 'אמת',
      'didnt_receive_code': 'לא קיבלת קוד?',
      'resend': 'שלח שוב',
      'code_resent': 'הקוד נשלח מחדש',
      'phone_verified': 'מספר הטלפון אומת',
      'new_password': 'סיסמה חדשה',
      'password_reset_success': 'הסיסמה אופסה בהצלחה',

      // User Types
      'renter': 'שוכר',
      'owner': 'בעלים',
      'office': 'משרד נדל"ן',
      'car_lessor': 'משכיר רכבים',

      // Status
      'pending_review': 'ממתין לבדיקה',
      'active': 'פעיל',
      'rejected': 'נדחה',
      'expired': 'פג תוקף',
      'paused': 'מושהה',

      // Plans
      'select_plan': 'בחר מסלול',
      'monthly': 'חודשי',
      'single_ad': 'מודעה אחת',
      'package': 'חבילה',
      'unlimited': 'ללא הגבלה',
      'listings': 'מודעות',
      'subscribe': 'הירשם',

      // Settings
      'settings': 'הגדרות',
      'language': 'שפה',
      'dark_mode': 'מצב כהה',
      'notifications': 'התראות',
      'privacy_policy': 'מדיניות פרטיות',
      'terms': 'תנאי שימוש',
      'about': 'אודות האפליקציה',

      // Messages
      'listing_created': 'המודעה נוצרה בהצלחה',
      'listing_updated': 'המודעה עודכנה',
      'added_to_favorites': 'נוסף למועדפים',
      'removed_from_favorites': 'הוסר מהמועדפים',
      'report_submitted': 'הדיווח נשלח',

      // Add Listing Form
      'add_new_listing': 'הוסף מודעה חדשה',
      'listing_type': 'סוג מודעה',
      'property_type': 'סוג נכס',
      'car_usage_type': 'סוג שימוש',
      'title': 'כותרת',
      'title_hint': 'הזן כותרת למודעה',
      'price_hint': 'הזן מחיר',
      'area_hint': 'הזן שטח במ"ר',
      'select_region': 'בחר אזור',
      'select_city': 'בחר עיר',
      'region': 'אזור',
      'city': 'עיר',
      'select_location_required': 'יש לבחור אזור ועיר',
      'agree_to': 'אני מסכים ל',
      'terms_of_service': 'תנאי שימוש',
      'delete_account': 'מחק חשבון',
      'delete_account_confirm':
          'האם אתה בטוח שברצונך למחוק את החשבון? כל הנתונים שלך יימחקו לצמיתות.',
      'enter_password_to_confirm': 'הזן סיסמה לאישור',
      'account_deleted': 'החשבון נמחק בהצלחה',
      'error_loading': 'שגיאה בטעינה',
      'address': 'כתובת',
      'address_hint': 'הזן כתובת מדויקת',
      'description_hint': 'הזן תיאור מפורט',
      'contact_phone': 'טלפון ליצירת קשר',
      'whatsapp_number': 'מספר וואטסאפ',
      'add_images': 'הוסף תמונות',
      'select_images': 'בחר תמונות',
      'max_images': 'מקסימום 10 תמונות',
      'submit_listing': 'פרסם מודעה',
      'brand': 'יצרן',
      'year': 'שנה',
      'color': 'צבע',
      'seats': 'מושבים',
      'daily_price': 'מחיר יומי',
      'weekly_price': 'מחיר שבועי',
      'monthly_price': 'מחיר חודשי',

      // Add Listing - Additional
      'apartment': 'דירה',
      'villa_chalet': 'וילה / שאלה',
      'shop_office': 'חנות / משרד',
      'land': 'קרקע',
      'required': 'חובה',
      'bathrooms_label': 'חדרי אמבטיה',
      'floor_label': 'קומה',
      'brand_label': 'מותג',
      'model_label': 'דגם',
      'year_label': 'שנת ייצור',
      'gearbox_label': 'תיבת הילוכים',
      'plate_color_label': 'צבע לוחית',
      'yellow': 'צהוב',
      'white': 'לבן',
      'green': 'ירוק',
      'price_label': 'מחיר (שקל)',
      'description_label': 'תיאור',
      'contact_phone_label': 'טלפון ליצירת קשר',
      'whatsapp_label': 'וואטסאפ',
      'free': 'חינם',
      'contact_us': 'צור קשר',
      'whatsapp_support': 'תמיכת וואטסאפ',

      // Welcome Bonus
      'welcome_title': 'ברוכים הבאים! 🎉',
      'welcome_bonus_title': 'קיבלת חבילת ברכה חינם!',
      'welcome_bonus_desc':
          'עכשיו אפשר להוסיף מודעה אחת בחינם.\nתהנה מהאפליקציה!',
      'start_now': 'התחל עכשיו',

      // Car Pricing
      'enter_one_price': 'הזן לפחות מחיר אחד',
      'daily': 'יומי',
      'weekly': 'שבועי',
      'rental_prices': 'מחירי השכרה',

      // Profile Screen - Subscriptions
      'my_active_subscriptions': 'המנויים הפעילים שלי',
      'view_all': 'הכל',
      'no_active_subscriptions': 'אין מנויים פעילים',
      'real_estate': 'נדל"ן',
      'vehicles': 'רכבים',
      'listings_remaining': 'נותרו',
      'listing_unit': 'מודעות',
      'days_remaining': 'נותרו',
      'day_unit': 'ימים',

      // My Subscriptions Screen
      'my_subscriptions': 'המנויים שלי',
      'active_tab': 'פעילים',
      'pending_tab': 'ממתינים',
      'history_tab': 'היסטוריה',
      'no_pending_subscriptions': 'אין מנויים ממתינים',
      'no_expired_subscriptions': 'אין היסטוריית מנויים',
      'general': 'כללי',
      'pending_approval': 'ממתין לאישור',
      'status_rejected': 'נדחה',
      'status_expired': 'פג תוקף',
      'status_cancelled': 'בוטל',
      'status_active': 'פעיל',
      'listings_label': 'מודעות',
      'days_remaining_label': 'ימים נותרים',
      'expiry_date': 'תאריך תפוגה',
      'subscription_date': 'תאריך הרשמה',

      // Checkout Screen
      'choose_package': 'בחר חבילה',
      'failed_load_packages': 'שגיאה בטעינת חבילות',
      'please_enter_sender_name': 'אנא הזן שם השולח',
      'pending_verification': 'ממתין לאישור',
      'transfer_received': 'קיבלנו את פרטי ההעברה. נאשר את התשלום תוך 24 שעות.',
      'purchase_success': 'הרכישה בוצעה בהצלחה!',
      'package_activated': 'החבילה הופעלה בחשבונך',
      'ok': 'אישור',
      'purchase_failed': 'הרכישה נכשלה',
      'unknown_error': 'שגיאה לא ידועה',
      'network_error': 'שגיאת רשת',
      'no_packages_available': 'אין חבילות זמינות',
      'swipe_to_see_more': 'החלק לראות עוד',
      'unlimited_listings': 'מודעות ללא הגבלה',
      'listings_count': 'מודעות',
      'days_validity': 'ימים תוקף',
      'featured_listing': 'מודעה מובלטת',
      'region_notifications': 'התראות אזוריות',
      'city_notifications': 'התראות עירוניות',
      'trusted_advertiser': 'מפרסם מהימן',
      'subscribe_now': 'הירשם',
      'payment_method': 'אמצעי תשלום',
      'bank_transfer': 'העברה בנקאית',
      'transfer_to_bank': 'העבר לחשבון הבנק שלנו',
      'fast_secure_payment': 'תשלום מהיר ומאובטח',
      'test_payment': 'תשלום לבדיקה',
      'test_only': 'לבדיקה בלבד',
      'bank_name': 'שם הבנק',
      'account_name': 'שם החשבון',
      'account_number': 'מספר חשבון',
      'sender_name': 'שם השולח',
      'confirm_and_pay': 'אשר ושלם',
      'test_mode_notice': 'מצב בדיקה - התשלום לא אמיתי',

      // Search Screen
      'filters': 'מסננים',
      'reset': 'איפוס',
      'all_regions': 'כל האזורים',
      'all_cities': 'כל הערים',
      'min_price': 'מחיר מינימלי',
      'max_price': 'מחיר מקסימלי',
      'min_bedrooms': 'חדרים מינימום',
      'min_area': 'שטח מינימלי',
      'search_results': 'תוצאות חיפוש',

      // Add Listing Screen
      'add_property_title': 'הוסף נכס',
      'add_car_title': 'הוסף רכב',
      'select_payment_or_package': 'אנא בחר אפשרות תשלום או רכוש חבילה',
      'listing_added_success': 'המודעה נוספה בהצלחה!',
      'listing_under_review':
          'המודעה שלך נמצאת כעת בבדיקה על ידי הצוות שלנו.\nתקבל התראה כשהמודעה תאושר ותפורסם.',
      'active_subscription': 'מנוי פעיל',
      'review_notice': 'המודעה שלך תיבדק על ידי הנהלה לפני הפרסום',
      'publish_listing': 'פרסם מודעה',
      'property_type_label': 'סוג נכס *',
      'title_label': 'כותרת',
      'title_example': 'לדוגמה: דירה יוקרתית להשכרה',
      'bedrooms_form': 'חדרי שינה',
      'area_form': 'שטח (מ"ר)',
      'floor_form': 'קומה',
      'brand_required': 'מותג *',
      'brand_example': 'לדוגמה: טויוטה',
      'model_required': 'דגם *',
      'model_example': 'לדוגמה: קמרי',
      'year_required': 'שנת ייצור *',
      'with_driver_label': 'עם נהג',
      'price_required': 'מחיר (שקל) *',
      'daily_price_label': 'מחיר יומי',
      'weekly_price_label': 'מחיר שבועי',
      'monthly_price_label': 'מחיר חודשי',
      'contact_phone_required': 'טלפון ליצירת קשר *',
      'whatsapp_optional': 'וואטסאפ (אופציונלי)',
      'description_optional': 'תיאור (אופציונלי)',
      'description_placeholder': 'הוסף תיאור למודעה...',
      'photos': 'תמונות',
      'add_photos': 'הוסף תמונות',
      'payment_options': 'אפשרויות תשלום',

      // Edit Listing Screen
      'edit_property': 'עריכת נכס',
      'edit_car': 'עריכת רכב',
      'rejection_reason': 'סיבת הדחייה:',
      'edit_and_resubmit': 'ערוך את המודעה ושלח אותה מחדש לבדיקה',
      'resubmit_for_review': 'שלח לבדיקה מחדש',
      'listing_sent_for_review': 'המודעה נשלחה לבדיקה!',

      // Chat Screen
      'message_failed': 'שליחת ההודעה נכשלה',
      'start_conversation': 'התחל שיחה',
      'send_message_to': 'שלח הודעה ליצירת קשר עם',
      'type_message': 'כתוב הודעה...',
      'no_conversations': 'אין שיחות',
      'no_conversations_hint': 'התחל שיחה מדף המודעה',
      'terms_conditions': 'תנאי שימוש',
      'user': 'משתמש',
      'now': 'עכשיו',

      // Auth (feature 002) — Arabic values verbatim per research § R-005.
      // Hebrew translations are a follow-up PR.
      'auth_error_invalid_credentials': 'رقم الهاتف أو كلمة المرور غير صحيحة',
      'auth_error_account_pending': 'حسابك قيد المراجعة من قبل الإدارة',
      'auth_error_account_blocked': 'تم حظر حسابك',
      'auth_error_email_exists': 'البريد الإلكتروني مستخدم مسبقاً',
      'auth_error_phone_exists': 'رقم الهاتف مستخدم مسبقاً',
      'auth_error_invalid_email': 'البريد الإلكتروني غير صالح',
      'auth_error_invalid_phone': 'رقم الهاتف غير صالح',
      'auth_error_weak_password': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'auth_error_missing_fields': 'يرجى إدخال جميع الحقول المطلوبة',
      'auth_error_validation_failed': 'يرجى التحقق من البيانات المدخلة',
      'auth_error_network': 'فشل الاتصال بالخادم',
      'auth_error_unknown_login': 'فشل تسجيل الدخول',
      'auth_error_unknown_register': 'فشل التسجيل',
      'auth_error_invalid_otp': 'رمز التحقق غير صحيح',
      'auth_error_expired_otp': 'انتهت صلاحية رمز التحقق',
      'user_type_renter': 'مستأجر',
      'user_type_owner': 'مالك عقار',
      'user_type_office': 'مكتب عقارات',
      'user_type_car_lessor': 'مؤجر سيارات',
      'must_accept_terms': 'يجب الموافقة على الشروط والأحكام',
      'account_under_review': 'حسابك قيد المراجعة',
      'verification_required': 'يتطلب التحقق',
      'verification_required_body': 'يرجى التحقق من بريدك الإلكتروني أو هاتفك',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'agree_to_terms_prefix': 'أوافق على ',
    },
    'en': {
      // General
      'app_name': 'Rento Go',
      'search': 'Search',
      'search_hint': 'Search city or area...',
      'filter': 'Filter',
      'all': 'All',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'close': 'Close',
      'confirm': 'Confirm',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'no_results': 'No results',

      // Tabs
      'properties': 'Properties',
      'cars': 'Cars',

      // Bottom Navigation
      'home': 'Home',
      'favorites': 'Favorites',
      'messages': 'Messages',
      'my_listings': 'My Listings',
      'profile': 'Profile',

      // Property Types
      'apartments': 'Apartments',
      'villas_chalets': 'Villas & Chalets',
      'shops_offices': 'Shops & Offices',
      'student_housing': 'Student Housing',
      'lands': 'Lands',

      // Car Types
      'daily_use': 'Daily Use',
      'wedding': 'Wedding',
      'tourism': 'Tourism',

      // CTA Banner
      'advertise_now': 'Advertise Now',
      'add_highlight_property': 'Add & Highlight Your Property',
      'add_highlight_car': 'Add & Highlight Your Car',
      'add_property': 'Add Properties',
      'add_car': 'Add Cars',
      'add_listing_button': 'Add Property or Car',

      // Listing Details
      'for_rent': 'For Rent',
      'price': 'Price',
      'negotiable': 'Negotiable',
      'area': 'Area',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'floor': 'Floor',
      'description': 'Description',
      'contact': 'Contact',
      'call': 'Call',
      'whatsapp': 'WhatsApp',
      'report': 'Report',

      // Car Details
      'model': 'Model',
      'gearbox': 'Gearbox',
      'automatic': 'Automatic',
      'manual': 'Manual',
      'with_driver': 'With Driver',
      'without_driver': 'Without Driver',
      'plate_color': 'Plate Color',
      'yellow_plate': 'Yellow',
      'white_plate': 'White',

      // Auth
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'phone': 'Phone',
      'name': 'Name',
      'edit_name': 'Edit Name',
      'edit_profile': 'Edit Profile',
      'name_required': 'Name is required',
      'name_too_short': 'Name is too short',
      'name_updated_successfully': 'Name updated successfully',
      'profile_updated_successfully': 'Profile updated successfully',
      'update_failed': 'Update failed',
      'security_settings': 'Security Settings',
      'change_password': 'Change Password',
      'change_email': 'Change Email',
      'change_phone': 'Change Phone',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'new_email': 'New Email',
      'new_phone': 'New Phone',
      'password_changed_successfully': 'Password changed successfully',
      'email_changed_successfully': 'Email changed successfully',
      'phone_changed_successfully': 'Phone changed successfully',
      'password_too_short': 'Password is too short',
      'invalid_phone': 'Invalid phone number',
      'required': 'Required',
      'company_name': 'Company Name',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'login_subtitle': 'Login to continue',
      'create_account': 'Create New Account',
      'register_subtitle': 'Create your account to start',
      'full_name': 'Full Name',
      'user_type': 'Account Type',
      'confirm_password': 'Confirm Password',
      'required_field': 'This field is required',
      'password_min_length': 'Password must be at least 6 characters',
      'passwords_not_match': 'Passwords do not match',
      'invalid_email': 'Invalid email',
      'no_account': "Don't have an account?",
      'have_account': 'Have an account?',
      'reset_password': 'Reset Password',
      'forgot_password_subtitle':
          'Enter your phone number to receive verification code',
      'send_code': 'Send Code',
      'verify_code': 'Verify Code',
      'enter_otp': 'Enter Verification Code',
      'code_sent_to': 'Code sent to',
      'enter_complete_code': 'Enter complete code',
      'verify': 'Verify',
      'didnt_receive_code': "Didn't receive code?",
      'resend': 'Resend',
      'code_resent': 'Code resent',
      'phone_verified': 'Phone verified',
      'new_password': 'New Password',
      'password_reset_success': 'Password reset successfully',

      // User Types
      'renter': 'Renter',
      'owner': 'Owner',
      'office': 'Real Estate Office',
      'car_lessor': 'Car Lessor',

      // Status
      'pending_review': 'Pending Review',
      'active': 'Active',
      'rejected': 'Rejected',
      'expired': 'Expired',
      'paused': 'Paused',

      // Plans
      'select_plan': 'Select Plan',
      'monthly': 'Monthly',
      'single_ad': 'Single Ad',
      'package': 'Package',
      'unlimited': 'Unlimited',
      'listings': 'Listings',
      'subscribe': 'Subscribe',

      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'privacy_policy': 'Privacy Policy',
      'terms': 'Terms & Conditions',
      'about': 'About App',

      // Messages
      'listing_created': 'Listing created successfully',
      'listing_updated': 'Listing updated',
      'added_to_favorites': 'Added to favorites',
      'removed_from_favorites': 'Removed from favorites',
      'report_submitted': 'Report submitted',

      // Add Listing Form
      'add_new_listing': 'Add New Listing',
      'listing_type': 'Listing Type',
      'property_type': 'Property Type',
      'car_usage_type': 'Usage Type',
      'title': 'Title',
      'title_hint': 'Enter listing title',
      'price_hint': 'Enter price',
      'area_hint': 'Enter area in sqm',
      'select_region': 'Select Region',
      'select_city': 'Select City',
      'region': 'Region',
      'city': 'City',
      'select_location_required': 'Please select region and city',
      'agree_to': 'I agree to ',
      'terms_of_service': 'Terms of Service',
      'delete_account': 'Delete Account',
      'delete_account_confirm':
          'Are you sure you want to delete your account? All your data will be permanently deleted.',
      'enter_password_to_confirm': 'Enter password to confirm',
      'account_deleted': 'Account deleted successfully',
      'error_loading': 'Error loading',
      'address': 'Address',
      'address_hint': 'Enter detailed address',
      'description_hint': 'Enter detailed description',
      'contact_phone': 'Contact Phone',
      'whatsapp_number': 'WhatsApp Number',
      'add_images': 'Add Images',
      'select_images': 'Select Images',
      'max_images': 'Maximum 10 images',
      'submit_listing': 'Submit Listing',
      'brand': 'Brand',
      'year': 'Year',
      'color': 'Color',
      'seats': 'Seats',
      'daily_price': 'Daily Price',
      'weekly_price': 'Weekly Price',
      'monthly_price': 'Monthly Price',

      // Add Listing - Additional
      'apartment': 'Apartment',
      'villa_chalet': 'Villa / Chalet',
      'shop_office': 'Shop / Office',
      'land': 'Land',
      'required': 'Required',
      'bathrooms_label': 'Bathrooms',
      'floor_label': 'Floor',
      'brand_label': 'Brand',
      'model_label': 'Model',
      'year_label': 'Year',
      'gearbox_label': 'Gearbox',
      'plate_color_label': 'Plate Color',
      'yellow': 'Yellow',
      'white': 'White',
      'green': 'Green',
      'price_label': 'Price (ILS)',
      'description_label': 'Description',
      'contact_phone_label': 'Contact Phone',
      'whatsapp_label': 'WhatsApp',
      'free': 'Free',
      'contact_us': 'Contact Us',
      'whatsapp_support': 'WhatsApp Support',

      // Welcome Bonus
      'welcome_title': 'Welcome! 🎉',
      'welcome_bonus_title': 'You got a free welcome bonus!',
      'welcome_bonus_desc':
          'You can now add one listing for free.\nEnjoy the app!',
      'start_now': 'Start Now',

      // Car Pricing
      'enter_one_price': 'Enter at least one price',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'rental_prices': 'Rental Prices',

      // Profile Screen - Subscriptions
      'my_active_subscriptions': 'My Active Subscriptions',
      'view_all': 'View All',
      'no_active_subscriptions': 'No active subscriptions',
      'real_estate': 'Real Estate',
      'vehicles': 'Vehicles',
      'listings_remaining': 'Remaining',
      'listing_unit': 'listings',
      'days_remaining': 'Remaining',
      'day_unit': 'days',

      // My Subscriptions Screen
      'my_subscriptions': 'My Subscriptions',
      'active_tab': 'Active',
      'pending_tab': 'Pending',
      'history_tab': 'History',
      'no_pending_subscriptions': 'No pending subscriptions',
      'no_expired_subscriptions': 'No expired subscriptions',
      'general': 'General',
      'pending_approval': 'Pending Approval',
      'status_rejected': 'Rejected',
      'status_expired': 'Expired',
      'status_cancelled': 'Cancelled',
      'status_active': 'Active',
      'listings_label': 'Listings',
      'days_remaining_label': 'Days Remaining',
      'expiry_date': 'Expiry Date',
      'subscription_date': 'Subscription Date',

      // Checkout Screen
      'choose_package': 'Choose Package',
      'failed_load_packages': 'Failed to load packages',
      'please_enter_sender_name': 'Please enter sender name',
      'pending_verification': 'Pending Verification',
      'transfer_received':
          'Transfer details received. We will verify and activate your package within 24 hours.',
      'purchase_success': 'Purchase Successful!',
      'package_activated': 'Package activated in your account',
      'ok': 'OK',
      'purchase_failed': 'Purchase Failed',
      'unknown_error': 'Unknown error',
      'network_error': 'Network error',
      'no_packages_available': 'No packages available',
      'swipe_to_see_more': 'Swipe to see more',
      'unlimited_listings': 'Unlimited listings',
      'listings_count': 'listings',
      'days_validity': 'days validity',
      'featured_listing': 'Featured listing',
      'region_notifications': 'Region notifications',
      'city_notifications': 'City notifications',
      'trusted_advertiser': 'Trusted advertiser',
      'subscribe_now': 'Subscribe Now',
      'payment_method': 'Payment Method',
      'bank_transfer': 'Bank Transfer',
      'transfer_to_bank': 'Transfer to our bank account',
      'fast_secure_payment': 'Fast and secure payment',
      'test_payment': 'Test Payment',
      'test_only': 'For testing only',
      'bank_name': 'Bank',
      'account_name': 'Account',
      'account_number': 'Account Number',
      'sender_name': 'Sender Name',
      'confirm_and_pay': 'Confirm & Pay',
      'test_mode_notice': 'Test mode - Payment is not real',

      // Search Screen
      'filters': 'Filters',
      'reset': 'Reset',
      'all_regions': 'All Regions',
      'all_cities': 'All Cities',
      'min_price': 'Min Price',
      'max_price': 'Max Price',
      'min_bedrooms': 'Min Bedrooms',
      'min_area': 'Min Area',
      'search_results': 'Search Results',

      // Add Listing Screen
      'add_property_title': 'Add Property',
      'add_car_title': 'Add Car',
      'select_payment_or_package':
          'Please select a payment option or purchase a package',
      'listing_added_success': 'Listing added successfully!',
      'listing_under_review':
          'Your listing is now under review by our team.\nYou will receive a notification when it is approved.',
      'active_subscription': 'Active Subscription',
      'review_notice':
          'Your listing will be reviewed by admin before publishing',
      'publish_listing': 'Publish Listing',
      'property_type_label': 'Property Type *',
      'title_label': 'Title',
      'title_example': 'Example: Luxury apartment for rent',
      'bedrooms_form': 'Bedrooms',
      'area_form': 'Area (m²)',
      'floor_form': 'Floor',
      'brand_required': 'Brand *',
      'brand_example': 'Example: Toyota',
      'model_required': 'Model *',
      'model_example': 'Example: Camry',
      'year_required': 'Year *',
      'with_driver_label': 'With Driver',
      'price_required': 'Price (ILS) *',
      'daily_price_label': 'Daily Price',
      'weekly_price_label': 'Weekly Price',
      'monthly_price_label': 'Monthly Price',
      'contact_phone_required': 'Contact Phone *',
      'whatsapp_optional': 'WhatsApp (optional)',
      'description_optional': 'Description (optional)',
      'description_placeholder': 'Add a description for your listing...',
      'photos': 'Photos',
      'add_photos': 'Add Photos',
      'payment_options': 'Payment Options',

      // Edit Listing Screen
      'edit_property': 'Edit Property',
      'edit_car': 'Edit Car',
      'rejection_reason': 'Rejection Reason:',
      'edit_and_resubmit': 'Edit the listing and resubmit for review',
      'resubmit_for_review': 'Resubmit for Review',
      'listing_sent_for_review': 'Listing sent for review!',

      // Chat Screen
      'message_failed': 'Failed to send message',
      'start_conversation': 'Start Conversation',
      'send_message_to': 'Send a message to contact',
      'type_message': 'Type a message...',
      'no_conversations': 'No Conversations',
      'no_conversations_hint': 'Start a conversation from a listing page',
      'terms_conditions': 'Terms & Conditions',
      'user': 'User',
      'now': 'Now',

      // Auth (feature 002) — Arabic values verbatim per research § R-005.
      // English translations are a follow-up PR.
      'auth_error_invalid_credentials': 'رقم الهاتف أو كلمة المرور غير صحيحة',
      'auth_error_account_pending': 'حسابك قيد المراجعة من قبل الإدارة',
      'auth_error_account_blocked': 'تم حظر حسابك',
      'auth_error_email_exists': 'البريد الإلكتروني مستخدم مسبقاً',
      'auth_error_phone_exists': 'رقم الهاتف مستخدم مسبقاً',
      'auth_error_invalid_email': 'البريد الإلكتروني غير صالح',
      'auth_error_invalid_phone': 'رقم الهاتف غير صالح',
      'auth_error_weak_password': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'auth_error_missing_fields': 'يرجى إدخال جميع الحقول المطلوبة',
      'auth_error_validation_failed': 'يرجى التحقق من البيانات المدخلة',
      'auth_error_network': 'فشل الاتصال بالخادم',
      'auth_error_unknown_login': 'فشل تسجيل الدخول',
      'auth_error_unknown_register': 'فشل التسجيل',
      'auth_error_invalid_otp': 'رمز التحقق غير صحيح',
      'auth_error_expired_otp': 'انتهت صلاحية رمز التحقق',
      'user_type_renter': 'مستأجر',
      'user_type_owner': 'مالك عقار',
      'user_type_office': 'مكتب عقارات',
      'user_type_car_lessor': 'مؤجر سيارات',
      'must_accept_terms': 'يجب الموافقة على الشروط والأحكام',
      'account_under_review': 'حسابك قيد المراجعة',
      'verification_required': 'يتطلب التحقق',
      'verification_required_body': 'يرجى التحقق من بريدك الإلكتروني أو هاتفك',
      'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
      'agree_to_terms_prefix': 'أوافق على ',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['ar']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'he', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key) => AppLocalizations.of(this).translate(key);
}
